Update workflow

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -9,6 +9,10 @@ on:
   push:
     branches: ["master"]
 
+  # Runs on any open or reopened pull request
+  pull_request:
+    types: [opened, reopened]
+
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
@@ -34,9 +38,20 @@ jobs:
       - name: Detect package manager
         id: detect-package-manager
         run: |
-          echo "manager=npm" >> $GITHUB_OUTPUT
-          echo "command=ci" >> $GITHUB_OUTPUT
-          echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager" >&2
+            exit 1
+          fi
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
@@ -67,6 +82,9 @@ jobs:
       - name: Show directory
         run: |
           ls -la
+      - name: Read next.config.mjs
+        run: |
+          cat next.config.mjs
 #      - name: Create directory aaaForCheck
 #        run: |
 #          mkdir ./aaaForCheck
